version: '3'

services:
  mysql:
    image: mysql:8.0  # 指定 MySQL 的版本為 8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:6.2  # 指定 Redis 的版本為 6.2
    environment:
      REDIS_PASSWORD: 123456
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
